### ISSUE TITLE
Misleading project

### ISSUE THREAD

**Issue by guillaumechereau** [goxel2/goxel2#23]
Author of Goxel here.

I just found this fork, and I have a few concerns.  While I encourage people to fork goxel for specific use case, here it seems all goxel "2" does it rebrand goxel by removing my name and all references to me and the original project (in a violation of the GPL license).

I think it would be fair to:

1. Not name it "goxel 2"
2. Make it clear that this is fork of goxel.  It should be written on top of the README file, with explanation of what the differences are.   The web page should also mention it, and the authors files should also not be modified to remove my name when virtually 100% of the code has been written by me.
3. Keep the original copyright header in the code, as required by the license !!
4. Collaborate with me so that improvements that would make sense to keep in goxel should be merged upstream.

Thanks.
Guillaume

**Comment by pegvin** [comment]
1. "goxel2", the license doesn't force me to use a same name but i'll rename the project to something else asap.
2. when you open the GitHub repo of goxel2 it's clearly visible: "forked from guillaumechereau/goxel", tho i have no problem adding it.
3. so the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly) indicates this is legally valid but not advised for practical reasons. so i'll put them back.
4. sure.

**Comment by bztsrc** [comment]
>  it seems all goxel "2" does it rebrand goxel by removing my name

That's just simply not true. Goxel2 does not violate the GPL, it attributes you. And it also implement LOTS of features you were too lazy to merge.

> Not name it "goxel 2"

This is not your repo, and the name "goxel" is not patented, nor a registered trademark (GPL wouldn't allow that anyway), so you have absolutely no say in that matter. If @pegvin wants to call this Goxel2, he has every right to do so.

> Keep the original copyright header in the code

Yes, that's required by the license, @pegvin must put those header comments back, adding a new "Copyright pegvin" line to the files he modified.

> Collaborate with me so that improvements that would make sense to keep in goxel should be merged upstream.

The reason for this for is because you were a jerk, unwilling to collaborate. Again, you have no say in this matter, and GPL does not require @pegvin to collaborate with you. If you want to backport something from this repo into yours, that's ENTIRELY UP TO YOU, you have no right to demand collaboration from pegvin.

Cheers,
bzt

**Comment by bztsrc** [comment]
@pegvin: Just to clearify what GPL demands from you,
1. you must add the name "guillaumechereau" and a link to https://github.com/guillaumechereau/goxel into AUTHORS.md, and 
2. mention that this is a fork in the README.md, and 
3. you should put the header comments back into the source files (preferably in the form mentioned in section [How to Apply These Terms to Your New Programs](https://www.gnu.org/licenses/gpl-3.0.en.html)).

However you can keep the name "Goxel2", and you have no obligation to mention being a fork on your webpage, and you have no obligation to collaborate with him either.

Cheers,
bzt

**Comment by pegvin** [comment]
@bztsrc thanks for clarifying all of the stuff, I'll just add the headers back, it doesn't really matter i just removed them to keep the code clean.

**Comment by guillaumechereau** [comment]
I am really choked by the animosity toward me here.  I am glad that a dev wants to keep the project alive, and I would have been more than welcome to work with pegvin either on a fork or to pass him the maintenance of goxel directly.  I just think it should have been done in a friendly matter.

**Comment by DMClVG** [comment]
Damn guys, GPL is all about collaboration. All the code is there and for anyone to use or fork, so what's the fuss about. @guillaumechereau doesn't have any obligation to accept any of the pull requests  (In fact, he could have made the project closed-source that would of been end of story), plus burn out is a real thing. No need to be so hostile

**Comment by bztsrc** [comment]
> I am really choked by the animosity toward me here.

You shouldn't be. Just think about how you treated people trying to collaborate with you.

> @guillaumechereau doesn't have any obligation to accept any of the pull requests

True, but it isn't about that. I know for a fact that I wasn't the only one, but I can only speak about my experience: he kept me waiting for months (!) and then silently closed my PR *without any explanation why*. Burn out or not, that was just very rude of him.

> he could have made the project closed-source

Yes, but he didn't, end of story.

He licensed it under GPL and abandoned it for years, refusing to accept any collaboration (in a very rude way, I must add). And yet, he is here now, being hostile, demanding renaming of this repo and demanding collaboration. This will not do.

I trust @pegvin understands what GPL expects of him, and he does all of that but nothing more. There's nothing more I can add to this topic, so I'm out.

Cheers,
bzt

**Comment by pegvin** [comment]
Ah man, it's converting to a mess, no hate to anyone, just wanted to continue this project and it seemed like origjnal author went silent so i forked it, i removed the headers because i like clean code but didn't knew that it's required.

And as for making the project closed source it was his choice and really i think i should consider rewriting this cause the code is a real mess to work with.

And as for bzt, i strongly favor him on the topic of collaboration, really you closed the pr and today you specified why you did so, and for real this model3d format has alot of potential.

Bruh i was celebrating rakhi and i saw wwe goin on here 😭

**Comment by guillaumechereau** [comment]
Well, the goxel format is indeed not very good I am the first to admit it.  But I am not going to replace it with another unknown format.  If one day glTF have support for voxel data I will then try to use as the default export format for sure.

**Comment by pegvin** [comment]
Done.
